# -*- mode: python -*-
# vi: set ft=python :

"""
Makes a system-installed LLVM headers and library available to be used as a
C/C++ dependency. On Ubuntu, pkg-config is used to locate the llvm headers and
library. On macOS, no pkg-config llvm.pc file is installed, but the llvm headers
are included in the macOS SDK and the library is always located at /usr/lib.

Example:
    WORKSPACE:
        load("@drake//tools/workspace/llvm:repository.bzl", "llvm_repository")
        llvm_repository(name = "foo")
    BUILD:
        cc_library(
            name = "foobar",
            deps = ["@foo//:llvm"],
            srcs = ["bar.cc"],
        )
Argument:
    name: A unique name for this rule.

"""

load("@drake//tools/workspace:execute.bzl", "execute_or_fail")
load("@drake//tools/skylark:pathutils.bzl", "join_paths")
load("@drake//tools/workspace:os.bzl", "determine_os")

HDRS_PATTERNS = [
    "include/**/*.h",
    "include/clang/Frontend/*.h",
    "include/**/*.def",
    "include/**/*.inc",
]

def _impl(repository_ctx):
    os_result = determine_os(repository_ctx)
    if os_result.error != None:
        fail(os_result.error)
    if os_result.is_macos:
        include = "/usr/local/opt/llvm/include"
        linkopts = ["-L/usr/local/opt/llvm/lib", "-lllvm"]
    else:
        include = "/usr/include"
        linkopts = ["-lllvm", "-ldl"]
    repository_ctx.symlink(
        include,
        "include",
    )
    file_content = """# -*- python -*-
# DO NOT EDIT: generated by llvm_repository()
licenses(["restricted"])  # LGPL 2.1
cc_library(
    name = "llvm",
    hdrs = glob({}),
    includes = ["include", "."],
    linkopts = {},
    visibility = ["//visibility:public"],
)
""".format(HDRS_PATTERNS, linkopts)
    repository_ctx.file(
        "BUILD.bazel",
        content = file_content,
        executable = False,
    )
llvm_repository = repository_rule(
    local = True,
    implementation = _impl,
)
